repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        exclude: ^(alembic/|venv/|\.venv/)

      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        exclude: ^(alembic/|venv/|\.venv/)


      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system
        types: [python]
        exclude: ^(alembic/|venv/|\.venv/)

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        exclude: ^(alembic/|venv/|\.venv/)
